### ISSUE TITLE
只有N卡才可以部署么？

### ISSUE THREAD

**Issue by niuroumiantt** [yuhaolove/ChatTTS-WebUI#1]
我用的是macOS M2 MAX 的芯片，32G 内存， 跑到最后一步就是：

## python webui/main.py
Load models from snapshot.
INFO:ChatTTS.core:Load from cache: /Users/yidian/.cache/huggingface/hub/models--2Noise--ChatTTS/snapshots/c0aa9139945a4d7bb1c84f07785db576f2bb1bfa
Traceback (most recent call last):
  File "/Users/yidian/ChatTTS-WebUI/webui/main.py", line 39, in <module>
    chat.load_models()
  File "/Users/yidian/ChatTTS-WebUI/ChatTTS/ChatTTS/core.py", line 55, in load_models
    self._load(**{k: os.path.join(download_path, v) for k, v in OmegaConf.load(os.path.join(download_path, 'config', 'path.yaml')).items()})
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yidian/PycharmProjects/pythonProject3/.venv/lib/python3.12/site-packages/omegaconf/omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/yidian/.cache/huggingface/hub/models--2Noise--ChatTTS/snapshots/c0aa9139945a4d7bb1c84f07785db576f2bb1bfa/config/path.yaml'
(chattts_webui) (.venv) yidian@ai ChatTTS-WebUI %

**Comment by niuroumiantt** [comment]
(chattts_webui) (.venv) yidian@ai ChatTTS-WebUI % python3 webui
/Users/yidian/PycharmProjects/pythonProject3/.venv/bin/python3: can't find '__main__' module in '/Users/yidian/ChatTTS-WebUI/webui'

**Comment by niuroumiantt** [comment]
/Users/yidian/PycharmProjects/pythonProject3/.venv/bin/python /Users/yidian/PycharmProjects/pythonProject3/ChatTTS-WebUI/ChatTTS-WebUI/webui/main.py 
Traceback (most recent call last):
  File "/Users/yidian/PycharmProjects/pythonProject3/ChatTTS-WebUI/ChatTTS-WebUI/webui/main.py", line 12, in <module>
    import ChatTTS
ModuleNotFoundError: No module named 'ChatTTS'

**Comment by niuroumiantt** [comment]
显示的问题和直接部署是一样的，就是 ModuleNotFoundError: No module named 'ChatTTS'

**Comment by yuhaolove** [comment]
这是模型文件没有下载完整

链接：https://pan.baidu.com/s/1A9BaB1S1DhMvmvzdJkViZA?pwd=sdru 
提取码：sdru 
--来自百度网盘超级会员V9的分享
